### ISSUE TITLE
Can please send me a tutorial video I could not make it run 

### ISSUE THREAD

**Issue by jomjom841** [AmalH/Codename-One---Cruds-with-MySQL-database#1]
please send me a tuto video to follow you

**Comment by AmalH** [comment]
Sure, here's the link : 
http://pragmatictheories.tech/codename-one-connecting-to-mysql-database-and-perfoming-basic-cruds/

**Comment by jomjom841** [comment]
okayy great it works , but the update method is not changing the lines in
database

2018-04-28 16:01 GMT+02:00 ArtPr <notifications@github.com>:
