### ISSUE TITLE
login & singup

### ISSUE THREAD

**Issue by mehdi420** [AmalH/Codename-One---Cruds-with-MySQL-database#2]
Salut , est ce que vous avez une application mobile code name one avec login & singup , ça peut vraiment m'aider?

**Comment by AmalH** [comment]
pass me your email i can send some samples

**Comment by mehdi420** [comment]
okay mercii , jolpojampa123@gmail.com

**Comment by mehdi420** [comment]
login & singup à partir d'une base de donnée biensure

**Comment by AmalH** [comment]
that's a weird email dude !  done I sent you some examples

**Comment by mehdi420** [comment]
do you have the php scripts of UserAuthDemo please ? :(
